companies = [
    # Ticker,FullName,Sector
    ("EGAD", "Eaagads Limited", "Agriculture"),
    ("KUKZ", "Kakuzi Limited", "Agriculture"),
    ("KAPC", "Kapchorua Tea Company Limited", "Agriculture"),
    ("LIMT", "Limuru Tea Company Limited", "Agriculture"),
    ("SASN", "Sasini Tea and Coffee", "Agriculture"),
    ("WTK", "Williamson Tea Kenya Limited", "Agriculture"),
    ("G&G", "Car & General Kenya", "Automobiles and Accessories"),
    ("FIRE", "Sameer Africa Limited", "Automobiles and Accessories"),
    ("BBK", "Barclays Bank of Kenya Banking", "Banking"),
    ("CFC", "CfC Stanbic Holdings ", "Banking"),
    ("DTK", "Diamond Trust Bank Group ", "Banking"),
    ("EQTY", "Equity Group Holdings Limited ", "Banking"),
    ("HFCK", "Housing Finance Company of Kenya ", "Banking"),
    ("I&M", "I&M Holdings Limited ", "Banking"),
    ("KCB", "Kenya Commercial Bank Group Banking & finance. ", "Banking"),
    ("NBK", "National Bank of Kenya ", "Banking"),
    ("NIC", "National Industrial Credit Bank", "Banking"),
    ("SCBK", "Standard Chartered of Kenya ", "Banking"),
    ("COOP", "Cooperative Bank of Kenya", "Banking"),
    ("BOK", "Bank of Kigali ", "Banking"),
    ("XPRS",  "Express Kenya Limited ", "Commercial and Services"),
    ("HBER",  "Hutchings Biemer Limited", "Commercial and Services"),
    ("KQ",  "Kenya Airways Kenya's flagship airline;", "Commercial and Services"),
    ("LKL",  "Longhorn Kenya Limited", "Commercial and Services"),
    ("NMG",  "Nation Media Group", "Commercial and Services"),
    ("SCAN",  "Scangroup", "Commercial and Services"),
    ("SGL",  "Standard Group Limited", "Commercial and Services"),
    ("TPSE",  "TPS Serena", "Commercial and Services"),
    ("UCHM",  "Uchumi Supermarkets", "Commercial and Services"),
    ("ARM",  "ARM Cement Limited", "Construction and Allied"),
    ("BAMB",  "Bamburi Cement Limited", "Construction and Allied"),
    ("BERG",  "Crown-Berger (Kenya)", "Construction and Allied"),
    ("CABL",  "East African Cables Limited", "Construction and Allied"),
    ("PORT",  "East Africa Portland Cement Company", "Construction and Allied"),
    ("KEGN", "Kengen", "Energy and Petroleum"),
    ("KENO", "KenolKobil", "Energy and Petroleum"),
    ("KPLC", "Kenya Power and Lighting Company", "Energy and Petroleum"),
    ("TOTL", "Total Kenya Limited ", "Energy and Petroleum"),
    ("UMME", "Umeme Electric power distribution", "Energy and Petroleum"),
    ("BRIT", "British-American Investments Company", "Insurance"),
    ("CIC", "CIC Insurance Group", "Insurance"),
    ("CFCI", "Liberty Kenya Holdings Limited (formally CFC Insurance)", "Insurance"),
    ("JUB", "Jubilee Holdings Limited", "Insurance"),
    ("KNRE", "Kenya Reinsurance Corporation", "Insurance"),
    ("PAFR", "Sanlam Kenya Plc (formally Pan Africa Insurance Holdings)", "Insurance"),
    ("ICDC", "Centum Investment Company", "Investment"),
    ("OCH", "Olympia Capital Holdings", "Investment"),
    ("TCL", "TransCentury Investments", "Investment"),
    ("NSE", "Nairobi Securities Exchange", "Investment Services"),
    ("BAUM", "A Baumann and Company Machinery", "Manufacturing and Allied"),
    ("BOC", "BOC Kenya Limited ", "Manufacturing and Allied"),
    ("BAT", "British American Tobacco Limited", "Manufacturing and Allied"),
    ("CARB", "Carbacid Investments Limited", "Manufacturing and Allied"),
    ("EABL", "East African Breweries", "Manufacturing and Allied"),
    ("EVRD", "Eveready East Africa", "Manufacturing and Allied"),
    ("ORCH", "Kenya Orchards Limited", "Manufacturing and Allied"),
    ("MSC", "Mumias Sugar Company Limited", "Manufacturing and Allied"),
    ("UNGA", "Unga Group ", "Manufacturing and Allied"),
    ("SCOM", "Safaricom Mobile", "Telecommunication and Technology"),
    ("ADSS", " Atlas Development & Support Services",
     "Growth Enterprise Market Segment"),
    ("HAFR", " Home Afrika Real estate", "Growth Enterprise Market Segment"),
    ("FTGH", " Flame Tree Group Holdings Ltd Consumer Goods",
     "Growth Enterprise Market Segment"),
    ("KVL", " Kurwitu Ventures Sharia investments", "Growth Enterprise Market Segment")]
