companies = [
    # Ticker,FullName,Sector
    {"ticker": "EGAD", "company": "Eaagads Limited", "industry": "Agriculture"},
    {"ticker": "KUKZ", "company": "Kakuzi Limited", "industry": "Agriculture"},
    {"ticker": "KAPC", "company": "Kapchorua Tea Company Limited",
        "industry": "Agriculture"},
    {"ticker": "LIMT", "company": "Limuru Tea Company Limited",
        "industry": "Agriculture"},
    {"ticker": "SASN", "company": "Sasini Tea and Coffee", "industry": "Agriculture"},
    {"ticker": "WTK", "company": "Williamson Tea Kenya Limited",
        "industry": "Agriculture"},
    {"ticker": "G&G", "company": "Car & General Kenya",
        "industry": "Automobiles and Accessories"},
    {"ticker": "FIRE", "company": "Sameer Africa Limited",
        "industry": "Automobiles and Accessories"},
    {"ticker": "BBK", "company": "Barclays Bank of Kenya Banking", "industry": "Banking"},
    {"ticker": "CFC", "company": "CfC Stanbic Holdings ", "industry": "Banking"},
    {"ticker": "DTK", "company": "Diamond Trust Bank Group ", "industry": "Banking"},
    {"ticker": "EQTY", "company": "Equity Group Holdings Limited ", "industry": "Banking"},
    {"ticker": "HFCK", "company": "Housing Finance Company of Kenya ",
        "industry": "Banking"},
    {"ticker": "I&M", "company": "I&M Holdings Limited ", "industry": "Banking"},
    {"ticker": "KCB", "company": "Kenya Commercial Bank Group Banking & finance. ",
        "industry": "Banking"},
    {"ticker": "NBK", "company": "National Bank of Kenya ", "industry": "Banking"},
    {"ticker": "NIC", "company": "National Industrial Credit Bank", "industry": "Banking"},
    {"ticker": "SCBK", "company": "Standard Chartered of Kenya ", "industry": "Banking"},
    {"ticker": "COOP", "company": "Cooperative Bank of Kenya", "industry": "Banking"},
    {"ticker": "BOK", "company": "Bank of Kigali ", "industry": "Banking"},
    {"ticker": "XPRS", "company": "Express Kenya Limited ",
        "industry": "Commercial and Services"},
    {"ticker": "HBER", "company": "Hutchings Biemer Limited",
        "industry": "Commercial and Services"},
    {"ticker": "KQ", "company": "Kenya Airways Kenya's flagship airline;",
        "industry": "Commercial and Services"},
    {"ticker": "LKL", "company": "Longhorn Kenya Limited",
        "industry": "Commercial and Services"},
    {"ticker": "NMG", "company": "Nation Media Group",
        "industry": "Commercial and Services"},
    {"ticker": "SCAN", "company": "Scangroup",
        "industry": "Commercial and Services"},
    {"ticker": "SGL", "company": "Standard Group Limited",
        "industry": "Commercial and Services"},
    {"ticker": "TPSE", "company": "TPS Serena",
        "industry": "Commercial and Services"},
    {"ticker": "UCHM", "company": "Uchumi Supermarkets",
        "industry": "Commercial and Services"},
    {"ticker": "ARM", "company": "ARM Cement Limited",
        "industry": "Construction and Allied"},
    {"ticker": "BAMB", "company": "Bamburi Cement Limited",
        "industry": "Construction and Allied"},
    {"ticker": "BERG",
        "company": "Crown-Berger (Kenya}", "industry": "Construction and Allied"},
    {"ticker": "CABL", "company": "East African Cables Limited",
        "industry": "Construction and Allied"},
    {"ticker": "PORT", "company": "East Africa Portland Cement Company",
        "industry": "Construction and Allied"},
    {"ticker": "KEGN", "company": "Kengen", "industry": "Energy and Petroleum"},
    {"ticker": "KENO", "company": "KenolKobil",
        "industry": "Energy and Petroleum"},
    {"ticker": "KPLC", "company": "Kenya Power and Lighting Company",
        "industry": "Energy and Petroleum"},
    {"ticker": "TOTL", "company": "Total Kenya Limited ",
        "industry": "Energy and Petroleum"},
    {"ticker": "UMME", "company": "Umeme Electric power distribution",
        "industry": "Energy and Petroleum"},
    {"ticker": "BRIT", "company": "British-American Investments Company",
        "industry": "Insurance"},
    {"ticker": "CIC", "company": "CIC Insurance Group", "industry": "Insurance"},
    {"ticker": "CFCI",
        "company": "Liberty Kenya Holdings Limited (formally CFC Insurance}", "industry": "Insurance"},
    {"ticker": "JUB", "company": "Jubilee Holdings Limited", "industry": "Insurance"},
    {"ticker": "KNRE", "company": "Kenya Reinsurance Corporation",
        "industry": "Insurance"},
    {"ticker": "PAFR",
        "company": "Sanlam Kenya Plc (formally Pan Africa Insurance Holdings}", "industry": "Insurance"},
    {"ticker": "ICDC", "company": "Centum Investment Company", "industry": "Investment"},
    {"ticker": "OCH", "company": "Olympia Capital Holdings", "industry": "Investment"},
    {"ticker": "TCL", "company": "TransCentury Investments", "industry": "Investment"},
    {"ticker": "NSE", "company": "Nairobi Securities Exchange",
        "industry": "Investment Services"},
    {"ticker": "BAUM", "company": "A Baumann and Company Machinery",
        "industry": "Manufacturing and Allied"},
    {"ticker": "BOC", "company": "BOC Kenya Limited ",
        "industry": "Manufacturing and Allied"},
    {"ticker": "BAT", "company": "British American Tobacco Limited",
        "industry": "Manufacturing and Allied"},
    {"ticker": "CARB", "company": "Carbacid Investments Limited",
        "industry": "Manufacturing and Allied"},
    {"ticker": "EABL", "company": "East African Breweries",
        "industry": "Manufacturing and Allied"},
    {"ticker": "EVRD", "company": "Eveready East Africa",
        "industry": "Manufacturing and Allied"},
    {"ticker": "ORCH", "company": "Kenya Orchards Limited",
        "industry": "Manufacturing and Allied"},
    {"ticker": "MSC", "company": "Mumias Sugar Company Limited",
        "industry": "Manufacturing and Allied"},
    {"ticker": "UNGA", "company": "Unga Group ",
        "industry": "Manufacturing and Allied"},
    {"ticker": "SCOM", "company": "Safaricom Mobile",
        "industry": "Telecommunication and Technology"},
    {"ticker": "ADSS", "company": " Atlas Development & Support Services",
     "industry": "Growth Enterprise Market Segment"},
    {"ticker": "HAFR", "company": " Home Afrika Real estate",
        "industry": "Growth Enterprise Market Segment"},
    {"ticker": "FTGH", "company": " Flame Tree Group Holdings Ltd Consumer Goods",
        "industry": "Growth Enterprise Market Segment"},
    {"ticker": "KVL", "company": " Kurwitu Ventures Sharia investments", "industry": "Growth Enterprise Market Segment"}]
